Human/Controllers/BaseController.cs
using Human.Common;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Human.Controllers
{
    public class BaseController : Controller
    {
        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            if (Session[CommonConstants.CurrentCulture] != null)
            {
                Thread.CurrentThread.CurrentCulture = new CultureInfo(Session[CommonConstants.CurrentCulture].ToString());
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(Session[CommonConstants.CurrentCulture].ToString());

            }
            else
            {
                Thread.CurrentThread.CurrentCulture = new CultureInfo("vi");
                Thread.CurrentThread.CurrentUICulture = new CultureInfo("vi");

            }
        }
        //changing culture
        public ActionResult ChangeCulture(string ddlCulture, string returnUrl)
        {
            Thread.CurrentThread.CurrentCulture = new CultureInfo(ddlCulture);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(ddlCulture);

            Session[CommonConstants.CurrentCulture] = ddlCulture;
            return Redirect(returnUrl);
        }
        protected override void OnActionExecuted(ActionExecutedContext context)
        {
            var session = Session["EMP_CODE"];
            if (session == null)
            {
                context.Result = new RedirectToRouteResult(new RouteValueDictionary(new { controller = "Login", action = "Index" }));
               
            }
            base.OnActionExecuted(context);


        }
        public string RenderPartialToString(string viewName, object model, ControllerContext ControllerContext)
        {
            if (string.IsNullOrEmpty(viewName))
                viewName = ControllerContext.RouteData.GetRequiredString("action");
            ViewDataDictionary ViewData = new ViewDataDictionary();
            TempDataDictionary TempData = new TempDataDictionary();
            ViewData.Model = model;

            using (StringWriter sw = new StringWriter())
            {
                ViewEngineResult viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                ViewContext viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);

                return sw.GetStringBuilder().ToString();
            }

        }
        protected bool IsEmail(string input)
        {
            // Biểu thức chính quy để kiểm tra địa chỉ email
            if (input != null)
            {
                string emailRegex = @"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b";
                return System.Text.RegularExpressions.Regex.IsMatch(input, emailRegex);
            }
            else
                return false;
        }

        protected bool IsUsername(string input)
        {
            // Biểu thức chính quy để kiểm tra tên người dùng
            string usernameRegex = @"^[A-Za-z0-9_]+$";
            return System.Text.RegularExpressions.Regex.IsMatch(input, usernameRegex);
        }
        protected void SetAlert(string message, string type)
        {
            TempData["AlertMessage"] = message;
            switch (type)
            {
                case "success":
                    TempData["AlertType"] = "alert-success"; break;
                case "warning":
                    TempData["AlertType"] = "alert-warning"; break;
                case "error":
                    TempData["AlertType"] = "alert-danger"; break;
                default: TempData["AlertType"] = ""; break;
            }
        }
    }
}

Human/Views/Shared/_Footer.cshtml
<!--<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">-->
@*<div class="d-flex align-items-center justify-content-between small">
        <div class="text-muted">Design by Sin Moste</div>
        <div>
            <a href="#">Privacy Policy</a>
            &middot;
            <a href="#">Terms &amp; Conditions</a>
        </div>
    </div>*@
<!--</div>
</footer>-->
<!-- ======= Footer ======= -->
@*<button onclick="topFunction()" id="myBtn" title="Go to top">TOP</button>

<style>

    #myBtn {
        display: none;
        position: fixed;
        bottom: 10px;
        right: 43px;
        z-index: 99;
        font-size: 18px;
        border: none;
        outline: none;
        background-color: blue;
        color: white;
        cursor: pointer;
        padding: 15px;
        border-radius: 4px;
    }

        #myBtn:hover {
            background-color: #555;
        }
</style>
*@

@*<script>
// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("myBtn").style.display = "block";
    } else {
        document.getElementById("myBtn").style.display = "none";
    }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
}
</script>*@

Human/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @RenderSection("meta", false)
    <title>@ViewBag.Title</title>
    <!-- datatable-->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" type="text/css">
    <link href="~/Assets/libs/datatables/dataTables.bootstrap4.css" rel="stylesheet" type="text/css" />
    <link href="~/Assets/css/default/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="~/Assets/css/styles.css?v=1.1" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <link href="~/Assets/css/Table.css?v=1.1" rel="stylesheet" type="text/css" />
    <link rel="icon" type="image/x-icon" href="~/Assets/img/logo_2.jpg" />
    <link href="~/Assets/css/MyStyle.css?v=1.1" rel="stylesheet" />
    <style>
        .swal2-container.swal2-center > .swal2-popup {
            font-size: 12px;
        }

        div.dataTables_wrapper div.dataTables_length select {
            min-height: 23px;
        }

        .dataTables_wrapper .dataTables_length select {
            border: none;
            border-bottom: 1px solid #b7b6b6;
            box-shadow: none;
            border-radius: 0;
        }

        .table-wrapper th:first-child {
            border-bottom-left-radius: 0px;
        }

        .table-wrapper th:last-child {
            border-bottom-right-radius: 0px;
        }

        .font-google {
            font-family: 'Montserrat', sans-serif;
        }
        
    </style>
</head>
<body class="sb-nav-fixed">
    <input class="hidden-item" type="hidden" value="@Session["EMP_CODE"]" id="emp_code_hidden" />
    <div id="layoutSidenav">
        @Html.Partial("_LeftMenu")

        <div id="layoutSidenav_content">

            @Html.Partial("_TopMenu")
            @RenderBody()

        </div>
        @Html.Partial("_Footer")
    </div>
    <!-- back to top -->
    <a id="button-back-top"><i style="font-size: 2em; font-weight: 600;color:#fff;margin-top:8px;" class="fa fa-angle-double-up"></i></a>
    <!-- javascript jquery -->
    <script src="~/Assets/js/jquery-3.6.3.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Assets/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="~/Assets/js/datatables-simple-demo.js"></script>
    @* sweet *@
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.2/dist/sweetalert2.all.min.js"></script>
    @*datatable*@
    <script src="~/Assets/libs/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Assets/libs/datatables/dataTables.bootstrap4.js"></script>
    <script src="~/Assets/libs/datatables/dataTables.responsive.min.js"></script>
    <script src="~/Assets/libs/datatables/responsive.bootstrap4.min.js"></script>
    <script src="~/Assets/libs/datatables/dataTables.buttons.min.js"></script>
    <script src="~/Assets/libs/datatables/buttons.bootstrap4.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
    <!-- Datatables init -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="~/Assets/js/pages/datatables.init.js"></script>
    @*js back to top*@
    <script src="~/Assets/js/admin/Back_top.js?v=1.1"></script>
    @*js admin dashboard*@
    <script src="~/Assets/js/admin/Common.js?v=1.1"></script>
    <script src="~/Assets/js/admin/EmailSMS.js?v=1.1"></script>
    <script src="~/Assets/js/admin/Upload_IMG.js?v=1.1"></script>
    <script src="~/Assets/js/admin/Colo_web.js?v=1.1"></script>
    @RenderSection("LoadJs", false)
</body>
</html>

Human/Views/Shared/_TopMenu.cshtml
@{
    var employee = Session["INFO_EMP"] as Human.Models.Entities.EmployeeView_Entities;
    var count_notifi = Session["COUNT_NOTIFI"];

    var random = new Random();
    var randomValue = random.Next().ToString();
    var language = "";
    if (Session[Human.Common.CommonConstants.CurrentCulture] != null)
    {
        language = Session[Human.Common.CommonConstants.CurrentCulture].ToString();
    }
    else
    {
        language = "vi";
    }
    var Session_pos = Session["EMP_POS"];

}

<nav class="sb-topnav navbar navbar-expand navbar-dark border-bottom">
    <div class="sidebar-toggle d-flex">
        <div class="logo-display" style="margin-top:8px;">
            <a class="ps-3 text-center" href="~/Home">
                <img style="width:80px; height:27px;" src="~/Assets/img/logo/logo.png?random=@randomValue" alt="logo website" />
            </a>
        </div>
        <button style="border-radius:10px;" class="btn order-1 order-lg-0 me-2 me-lg-0" id="sidebarToggle">
            <i class="fas fa-bars"></i><i style="display:none;" class="fas fa-chevron-left"></i> Menu
        </button>
        <div class="d-flex justify-content-between ms-auto me-0 me-md-3 my-2 my-md-0" style="margin-right:0px !important;">
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <!-- Notifications -->
                @if (Session["EMP_POS"] != "")
                {
                    <li class="nav-item dropdown has-arrow flag-nav">
                        <a style="padding-right:25px;" class="nav-link" data-bs-toggle="dropdown" href="#" role="button" id="navbarDropdown_notifi" aria-expanded="false">
                            <i class="fas fa-bell" style="height:15px;"></i> <span class="badge badge-pill notifi-sum" style="border-radius: 10rem; right: 4px; top: -3px;">@count_notifi</span>
                        </a>
                        <div class="dropdown-menu notifications" aria-labelledby="navbarDropdown_notifi">
                            <div class="topnav-dropdown-header">
                                <span class="notification-title">@Human.Resource.Language.Notification</span>
                                <a href="#" class="clear-noti"> @Human.Resource.Language.Clear_All </a>
                            </div>
                            <div class="noti-content">
                                <ul class="notification-list">
                                    @if (Convert.ToInt32(count_notifi) != 0)
                                    {
                                        <li class="notification-message">
                                            <a href="~/Notification/Index">
                                                <div class="media">
                                                    @*    <span class="avatar">
                                                        <img alt="" src="assets/img/profiles/avatar-02.jpg">
                                                    </span>*@
                                                    <div class="media-body">
                                                        <p class="noti-details  font-14" style="color:red;"><span class="noti-title font-13"></span> @count_notifi <span class="noti-title font-13">@Human.Resource.Language.Emp_request_cancel_leave</span></p>
                                                        @*<p class="noti-time"><span class="notification-time">4 mins ago</span></p>*@
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                    }
                                    else
                                    {
                                        <li class="notification-message"><div class="font-14 font-weight-bold" style="text-align:center;margin:15px;">@Human.Resource.Language.No_notification</div></li>
                                    }
                                    @*<li class="notification-message">
                                        <a href="activities.html">
                                            <div class="media">
                                               <span class="avatar">
                                                    <img alt="" src="assets/img/profiles/avatar-03.jpg">
                                                </span>
                                                <div class="media-body">
                                                    <p class="noti-details"><span class="noti-title">Tarah Shropshire</span> changed the task name <span class="noti-title">Appointment booking with payment gateway</span></p>
                                                    <p class="noti-time"><span class="notification-time">6 mins ago</span></p>
                                                </div>
                                            </div>
                                        </a>
                                    </li>*@
                                </ul>
                            </div>
                            <div class="topnav-dropdown-footer">
                                <a href="#">@Human.Resource.Language.View_all_Notifications</a>
                            </div>
                        </div>
                    </li>
                }
                <!-- /Notifications -->
                <!-- Flag -->
                <li class="nav-item dropdown has-arrow flag-nav" style="padding-right:5px">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" id="navbarDropdown1" aria-expanded="false">
                        @if (language == "vi")
                        {
                            <img src="~/Assets/img/flags/Vietnam-64.png" alt="" height="14">

                            <span class="font-14" style="text-transform: uppercase;">
                                @Human.Resource.Language.Vietnamese_show
                            </span>
                        }
                        else if (language == "en")
                        {
                            <img src="~/Assets/img/flags/us.png" alt="" height="18">

                            <span class="font-14" style="text-transform: uppercase;">
                                @Human.Resource.Language.English_show
                            </span>
                        }

                    </a>
                    <div style="padding:5px 0px;" class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown1">
                        <a href="@Url.Action("ChangeCulture", "Base", new { ddlCulture = "vi", returnUrl = "/Home" })" class="dropdown-item">
                            <img src="~/Assets/img/flags/flag-vietnam-24.png" alt="" height="16"> @Human.Resource.Language.Vietnamese
                        </a>
                        <a href="@Url.Action("ChangeCulture", "Base", new { ddlCulture = "en", returnUrl = "/Home" })" class="dropdown-item">
                            <img src="~/Assets/img/flags/us.png" alt="" height="16"> @Human.Resource.Language.English
                        </a>
                    </div>
                </li>
                <!-- /Flag -->
                <li class="nav-item dropdown d-flex">
                    <a style="padding-bottom:5px;" class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <span>
                            <img style="border-radius:50%; width:30px;height:30px;" src="~/Assets/img/avatar/@(employee.IMG_WEB != null ? employee.IMG_WEB+ "?random=" + randomValue :"user.png"+"?random=" + randomValue)" alt="user">
                            @*<span class="status-online"></span>*@
                        </span>
                        <b class="name-header">@employee.FULLNAME</b>
                    </a>
                    @*  <i class="fas fa-user fa-fw text-black"></i>*@
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li>
                            <div class="dropdown-item" style="padding:0px;">
                                <a class="border-bottom dropdown-item-text">
                                    <p style="margin-bottom:0;">@employee.FULLNAME</p>
                                    <p style="margin-bottom:0;">@employee.EMP_CODE</p>
                                    <p style="margin-bottom:0;"> @employee.TitleName_en</p>
                                </a>
                            </div>
                        </li>
                        <li><a class="dropdown-item" href="~/ProfileEmployee/Index">@Human.Resource.Language.Profile</a></li>
                        <li><a class="dropdown-item" href="#" onclick="Logout()">@Human.Resource.Language.Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>

    </div>
</nav>