Human/Areas/Admin/Controllers/LeaveController.cs
using Human.Areas.Admin.Models;
using Human.Controllers;
using Human.Models;
using Human.DO;
using Human.Models.Entities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http.Headers;
using System.Reflection;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace Human.Areas.Admin.Controllers
{
    public class LeaveController : BaseController
    {
        LeaveModel model = new LeaveModel();
        LEAVE_DO leave_DO;
        Employee_DO _empDO;
        public KindLeave_DO kindLeave_DO;
        // GET: Admin/Leave
        public ActionResult Index()
        {
            init();

            return View(model);
        }
        public void init()
        {
            kindLeave_DO = new KindLeave_DO();
            leave_DO = new LEAVE_DO();
            _empDO = new Employee_DO();

            KindLeave_Entities tempK = new KindLeave_Entities();
            tempK.KINDLEAVE_ID = 0;
            tempK.NAMELEAVE_VI = "Tất cả";
            tempK.NAMELEAVE_EN = "ALL";
            model.LST_KINDLEAVE = kindLeave_DO.GetAllKindLeave().ToList();
            model.LST_KINDLEAVE.Add(tempK);

            model.POSITION = ClsGlobal_Entities.POS; 
        }
       

        public ActionResult Search([FromBody] AdminLeaveModel modelBody, string KINDLEAVE_ID)
        {
            init();
            string condition = "";
            if (modelBody.SEARCH_CODE != "" && modelBody.SEARCH_CODE != null)
            {
                condition += " AND EMP.EMP_CODE='" + modelBody.SEARCH_CODE + "'";
                Session["SEARCH_CODE"] = modelBody.SEARCH_CODE;

            }
            else
            {
                Session["SEARCH_CODE"] = null;
            }
            if (modelBody.SEARCH_STARTDATE <= modelBody.SEARCH_ENDDATE)
            {
                condition += " AND LEAVE_STARTDATE BETWEEN '" + modelBody.SEARCH_STARTDATE.ToString("yyyy-MM-dd") + "' AND '" + modelBody.SEARCH_ENDDATE.ToString("yyyy-MM-dd") + "'";
                Session["SEARCH_START"] = modelBody.SEARCH_STARTDATE;
                Session["SEARCH_END"] = modelBody.SEARCH_ENDDATE;
            }
            if(modelBody.SEARCH_STATUSLEAVE >= 0)
            {
                condition += " AND STATUS_L = " + modelBody.SEARCH_STATUSLEAVE.ToString();
                Session["SEARCH_STATUS"] = modelBody.SEARCH_STATUSLEAVE;
            }
            else
            {
                Session["SEARCH_STATUS"] = null;

            }
            if (KINDLEAVE_ID != "0")
            {
                condition += "AND LEAVE_TAB.KINDLEAVE_ID = " + KINDLEAVE_ID + "";
                Session["SEARCH_KL_ID"] = KINDLEAVE_ID;
            }
            else
            {
                Session["SEARCH_KL_ID"] = "0";
            }
            leave_DO = new LEAVE_DO();
            model.LST_LEAVEVIEW = leave_DO.SP_SEL_LEAVE_MODEL(condition).OrderBy(o => o.LEAVE_STARTDATE).ToList();
            return View("Index", model);


        }
       
        
       
       
        public void GetLeaveCurrent()
        {

            string condition = "";
            
            if (Session["SEARCH_CODE"] != null)
            {
                condition += " AND EMP.EMP_CODE='" + Session["SEARCH_CODE"] + "'";

            }

            condition += " AND LEAVE_STARTDATE BETWEEN '" + Convert.ToDateTime(Session["SEARCH_START"]).ToString("yyyy-MM-dd") + "' AND '" + Convert.ToDateTime(Session["SEARCH_END"]).ToString("yyyy-MM-dd") + "'";
            if (Session["SEARCH_STATUS"] != null)
            {
                condition += " AND STATUS_L= " + Session["SEARCH_STATUS"].ToString();
            }
            if (Session["SEARCH_KL_ID"].ToString() != "0")
            {
                condition += "AND LEAVE_TAB.KINDLEAVE_ID = " + Session["SEARCH_KL_ID"] + "";
            }
            leave_DO = new LEAVE_DO();
            model.LST_LEAVEVIEW = leave_DO.SP_SEL_LEAVE_MODEL(condition).OrderBy(o => o.LEAVE_STARTDATE).ToList();
        }

       

        // GET: Admin/Leave/Create
        public ActionResult Create()
        {
            init();
            return View(model);
        }

        // POST: Admin/Leave/Create


        // GET: Admin/Leave/Edit/5
        public ActionResult Edit(int LEAVE_ID)
        {
            init();
            leave_DO = new LEAVE_DO();
            model.T_Leave = leave_DO.GetLeaveById(LEAVE_ID).FirstOrDefault();
            return View(model);
        }
        public ActionResult InsertLeave([FromBody] Leave_Entities sp)
        {
            try
            {
                _empDO = new Employee_DO();
                leave_DO = new  LEAVE_DO();
                var emp = _empDO.GetEmployeeByCode(sp.EMP_CODE).FirstOrDefault();
                if (emp != null && sp.EMPLOYEE_ID == emp.EMPLOYEE_ID)
                {
                    string pos = ClsGlobal_Entities.POS;
                    sp.COM_YEAR_MONTH = sp.COM_YEAR + sp.COM_MONTH;
                    int i = leave_DO.INS_LEAVE_ADMIN(sp,pos);
                    if (i > 0)
                    {
                        SetAlert("Thêm mới phép thành công", "success");
                    }
                    else
                    {
                        SetAlert("Thêm mới Thất bại", "alert-error");
                        return RedirectToAction("Create");
                    }
                }
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }


        public void UpdateStatusLeave(int LEAVE_ID, int STATUS)
        {
            if (Session["EMP_ID"] != null)
            {
                string pos = ClsGlobal_Entities.POS;
                int emp_id = Convert.ToInt32(Session["EMP_ID"]);
                leave_DO = new LEAVE_DO();
                leave_DO.UPD_LEAVE_STATUS(pos, LEAVE_ID, STATUS, emp_id);
            }
        }
        public bool UpdateKindLeave(int LEAVE_ID,int KINDLEAVE_ID,int EMPLOYEE_ID)
        {
            Leave_Entities l = new Leave_Entities();
            Cal_Leave_Entities cal_Leave = new Cal_Leave_Entities();
            l.LEAVE_ID = LEAVE_ID;
            l.KINDLEAVE_ID = KINDLEAVE_ID;
            leave_DO = new LEAVE_DO();
            if (KINDLEAVE_ID == 1)
            {
                cal_Leave = leave_DO.SEL_CAL_LEAVE("AND EMPLOYEE_ID=" + EMPLOYEE_ID.ToString()).FirstOrDefault();
                if (cal_Leave != null && cal_Leave.REMAIN <= 0)
                {
                    return false;
                }
              
            }
                leave_DO.UPD_LEAVE_KINDLEAVE(l);
                return true;
           

        }
        public ActionResult ReloadTotalLeave()
        {
            leave_DO = new LEAVE_DO();
            string year_now = DateTime.Now.Year.ToString();
            int i = leave_DO.SP_TOTAL_LEAVE("%", "%", "%", year_now);
            Session.Clear();
            return RedirectToAction("Index");
        }
        public JsonResult LoadLeaveUpdate()
        {
            init();
            GetLeaveCurrent();
            return Json(model,JsonRequestBehavior.AllowGet);
        }

    }
}

Human/Controllers/LeaveController.cs
using Human.Models;

using Human.DO;
using Human.Models.Entities;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using Human.Common;

namespace Human.Controllers
{
    public class LeaveController : BaseController
    {
        // GET: Leave
        KindLeaveModel model = new KindLeaveModel();
        LEAVE_DO leave_DO;
        Employee_DO _empDO;
        public KindLeave_DO kindLeave_DO;
        public ActionResult Index()
        {

            init();
          
            return View(model);
        }
        public void init()
        {
            try
            {
                kindLeave_DO = new KindLeave_DO();
                leave_DO = new LEAVE_DO();
                _empDO = new Employee_DO();


                string year = DateTime.Now.ToString("yyyy");
                int i = leave_DO.SP_TOTAL_LEAVE("%", "%", "%", year);

                model.LST_KINDLEAVE = kindLeave_DO.GetAllKindLeave().ToList();
                var emp_code = Session["EMP_CODE"];
                string con_str = "";
                if (emp_code != null)
                {
                    con_str += " AND EMP_CODE='" + emp_code + "'";
                    var emp = _empDO.GetInfoEmployee(con_str).FirstOrDefault();
                    if (emp != null)
                    {

                        var emp_id = emp.EMPLOYEE_ID;
                        string condition = "AND EMPLOYEE_ID =" + emp_id;

                        ViewBag.EmployeeID = emp_id;
                        model.EMPLOYEE = emp;
                        model.LST_LEAVE = leave_DO.GetLeaveByEmployeeId(emp_id).Where(w => w.LEAVE_STARTDATE.Year == DateTime.Now.Year).OrderByDescending(o => o.LEAVE_STARTDATE).ToList();
                        model.TOTAL_LEAVE = leave_DO.SEL_CAL_LEAVE(condition).FirstOrDefault();
                        
                    }

                }
                else
                {

                }




            }
            catch (Exception ex)
            {

            }
        }

        public ActionResult Add()
        {

            init();
            return View(model);
        }
        public ActionResult Edit(int LEAVE_ID)
        {

            init();
            model.T_Leave = model.LST_LEAVE.Where(w => w.LEAVE_ID == LEAVE_ID).FirstOrDefault();

            return View(model);

        }
        [ValidateAntiForgeryToken]
        public ActionResult InsertLeave([FromBody] Leave_Entities sp)
        {
            try
            {
                if (sp.CHECKED_TODATE == false)
                {
                    sp.LEAVE_ENDDATE = sp.LEAVE_STARTDATE;
                }

                _empDO = new Employee_DO();
                leave_DO = new LEAVE_DO();
                string con_email = " AND EMP_CODE ='" + Session["EMP_CODE"].ToString() + "'";
                var emp = _empDO.GetEmployeeByCondition(con_email).FirstOrDefault();
                if (emp != null && sp.EMPLOYEE_ID == emp.EMPLOYEE_ID)
                {

                    sp.COM_YEAR_MONTH = sp.COM_YEAR + sp.COM_MONTH;
                    float PNCL = leave_DO.SEL_ANUAL_LEAVE_REMAIN(sp.EMPLOYEE_ID);
                    if (sp.KINDLEAVE_ID == 1 && TotalLeaveInsert(sp.LEAVE_STARTDATE, sp.LEAVE_ENDDATE, (float)sp.HOURS, PNCL) < 0)
                    {
                        CommonCheck.SetAlert(this,"Phép năm của bạn không đủ. Lưu không thành công!", "warning");


                    }
                    else if (Max3_DateLeave(sp.LEAVE_STARTDATE, sp.LEAVE_ENDDATE))
                    {
                        CommonCheck.SetAlert(this,"Tối đa là 3 ngày phép. Lưu không thành công!", "warning");
                    }
                    else
                    {
                        string condition = " AND LEAVE_TAB.LEAVE_STARTDATE between'" + sp.LEAVE_STARTDATE.ToString("yyyy-MM-dd") + "' and '" + sp.LEAVE_ENDDATE.ToString("yyyy-MM-dd") + "'";

                        if (sp.EMPLOYEE_ID > 0)
                            condition += " AND LEAVE_TAB.EMPLOYEE_ID = " + sp.EMPLOYEE_ID;
                        if (sp.LEAVE_ID > 0)
                            condition += " AND LEAVE_ID =" + sp.LEAVE_ID;

                        List<Leave_Entities> leave_CHECK = leave_DO.SEL_LEAVE(condition).ToList();
                        foreach (Leave_Entities leave in leave_CHECK)
                        {
                            if (leave.STATUS_L != 0)
                            {
                                CommonCheck.SetAlert(this,Human.Resource.Language.This_leave_date_has_been_confirmed, "error");
                                
                                return RedirectToAction("Index");
                            }
                        }

                        int i = 0;
                        if (sp.LEAVE_ID > 0)
                        {
                            i = leave_DO.UPD_LEAVE(sp);
                            if (i > 0)
                            {
                                CommonCheck.SetAlert(this,Human.Resource.Language.Update_leave_successful, "success");
                            }
                            else
                            {
                                CommonCheck.SetAlert(this,Human.Resource.Language.Update_leave_failed, "error");

                            }
                        }
                        else
                        {
                            i = leave_DO.INS_Leave(sp);
                            if (i > 0)
                            {
                                CommonCheck.SetAlert(this,Human.Resource.Language.Add_new_leave_successful, "success");
                            }
                            else
                            {
                                CommonCheck.SetAlert(this,Human.Resource.Language.Add_new_leave_failed, "error");

                            }
                        }


                    }
                }

            }
            catch (Exception ex)
            {
                CommonCheck.SetAlert(this,"Error!!!!", "error");
            }
            finally
            {

            }


            return RedirectToAction("Index");
        }

        public float TotalLeaveInsert(DateTime StartDate, DateTime EndDate, float Hours, float PNCL)
        {
            float total_Phep;
            int total_day = 0;
            for (DateTime dt_temp = StartDate; dt_temp <= EndDate; dt_temp = dt_temp.AddDays(1))
            {
                if (dt_temp.DayOfWeek != DayOfWeek.Sunday)
                {
                    total_day++;
                }
            }
            total_Phep = (total_day * (Hours / 8));
            return PNCL - total_Phep;
        }
        public bool Max3_DateLeave(DateTime start, DateTime end)
        {
            //tính cả ngày bắt đầu nên tổng ngày chỉ là 2. vd: 1>3 -> 2
            TimeSpan timediff = end - start;
            if (timediff.TotalDays > 2)
                return true;
            else
                return false;
        }
        public ActionResult Delete(string LEAVE_ID)
        {
            leave_DO = new LEAVE_DO();
            int i = leave_DO.Delete(Convert.ToInt32(LEAVE_ID));
            if (i > 0)
            {
                CommonCheck.SetAlert(this,Human.Resource.Language.Delete_successfully, "success");
            }
            else
            {
                CommonCheck.SetAlert(this,Human.Resource.Language.Delete_failed, "error");
            }
            return RedirectToAction("Index");
        }
        public ActionResult Request(string LEAVE_ID)
        {
            leave_DO = new LEAVE_DO();
            int i = leave_DO.Request(Convert.ToInt32(LEAVE_ID));
            if (i > 0)
            {
                CommonCheck.SetAlert(this,Human.Resource.Language.Request_sent_successfully, "success");
            }
            else
            {
                CommonCheck.SetAlert(this,Human.Resource.Language.Request_sent_failed, "error");
            }
            return RedirectToAction("Index");
        }
      
        public ActionResult Cancel(string LEAVE_ID)
        {
            leave_DO = new LEAVE_DO();
            int i = leave_DO.Cancel(Convert.ToInt32(LEAVE_ID));
            if (i > 0)
            {
                CommonCheck.SetAlert(this, Human.Resource.Language.Cancel_leave_successfully, "success");

            }
            else
            {
                CommonCheck.SetAlert(this, Human.Resource.Language.Cancel_leave_failed, "error");

            }
            return RedirectToAction("Index");
        }

        public int DeleteById(string LEAVE_ID)
        {
            leave_DO = new LEAVE_DO();
            int i = leave_DO.Delete(Convert.ToInt32(LEAVE_ID));
            if (i > 0)
            {
                CommonCheck.SetAlert(this, Human.Resource.Language.Delete_successfully, "success");

            }
            else
            {
                CommonCheck.SetAlert(this, Human.Resource.Language.Delete_failed, "error");

            }
            return i;
        }
        public JsonResult PNCL(string EMPLOYEE_ID)
        {
            leave_DO = new LEAVE_DO();
            float pncl = leave_DO.SEL_ANUAL_LEAVE_REMAIN(Convert.ToDecimal(EMPLOYEE_ID));
            return Json(pncl, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetListLeaveByMonth(int month)
        {
            init();
            if (month != 0)
            {
                model.LST_LEAVE = model.LST_LEAVE.Where(w => w.LEAVE_STARTDATE.Month == month && w.STATUS_L==1 && w.KINDLEAVE_ID==1).OrderByDescending(o => o.LEAVE_STARTDATE).ToList();

            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        public JsonResult LoadLeave()
        {
            init();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

Human/Areas/Admin/Views/Leave/Create.cshtml
@model Human.Areas.Admin.Models.LeaveModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Phép";
    ViewBag.active = 3;
}
@section meta{
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="quản lý bảng lương" />
    <meta name="author" content="" />

}

@section LoadJs{
    <script src="~/Areas/Admin/Assets/JS/Leave.js"></script>
}
@{
    var formatString = "{0:0,0}";
    var date_now = DateTime.Now.ToString("yyyy-MM-dd");
}

<div class="container">
    <div class="form">
        <div class="btn-back"><a href="~/Admin/Leave/Index"><i class="fa fa-arrow-left"></i></a></div>

        <div class="card-header leave-header">


            @using (Html.BeginForm("InsertLeave", "Leave", FormMethod.Post))
            {
                <input type="hidden" value="@ViewBag.EmployeeID" name="EMPLOYEE_ID" id="EMPLOYEE_ID" />
                <input type="hidden" name="PNCL" id="PNCL" />
                <div class="row col-12">
                    <div class="col-lg-5 col-12">
                        <label class="header-child col-lg-3 col-5">Mã NV:</label>
                        <input class="col-lg-6 col-6" name="EMP_CODE" id="EMP_CODE" required/>
                        <a class="leave-btn color-blue-light" id="CHECK_EMPCODE">Kiểm tra</a>
                    </div>
                    <div class="col-lg-5 col-12">
                        <label class="header-child col-lg-3 col-5">Tên NV:</label>
                        <label class="col-lg-6 col-6" name="FULLNAME" id="NAME_EMP"></label>

                    </div>
                </div>
                <div class="row col-12">
                    <div class="col-lg-5 col-12">
                        <label class="header-child col-lg-3 col-5">Loại phép:</label>
                        <select class="col-lg-6 col-6" name="KINDLEAVE_ID">
                            @foreach (var item in Model.LST_KINDLEAVE)
                            {
                                <option value="@item.KINDLEAVE_ID">@item.NAMELEAVE_VI</option>
                            }

                        </select>
                    </div>
                </div>
                <div class="row col-12">
                    <div class="col-lg-5 col-12 ">
                        <label class="header-child col-lg-3  col-5">Từ ngày:</label>
                        <input type="date" class="col-lg-6 col-6" name="LEAVE_STARTDATE" value="@date_now" />
                    </div>
                    <div class="col-lg-5 col-12">
                        <label class="header-child col-lg-3  col-5">Đến ngày:</label>
                        <input type="date" class="col-lg-6 col-6" name="LEAVE_ENDDATE" value="@date_now" />
                    </div>
                </div>
                <div class="row col-12 ">
                    <div class="col-lg-5 col-12">
                        <label class="header-child col-lg-3 col-5">Số giờ:</label>
                        <select class="col-lg-6 col-6" name="HOURS">
                            <option value="4">4</option>
                            <option value="8">8</option>
                        </select>
                    </div>
                    <div class="col-4 hidden-item">
                        <label class="header-child col-lg-5">Compt for month:</label>
                        <input class="col-lg-6 col-6" name="COM_MONTH" value="" />
                    </div>
                    <div class="col-4 hidden-item">
                        <label class="header-child col-3">year:</label>
                        <input class="col-6 col-6" name="COM_YEAR" value="" />
                    </div>
                </div>
                <div class="row col-12">
                    <div class="col-lg-5 col-12">
                        <label class="header-child col-lg-3 col-5">Lý do:</label>

                        <textarea type="text" class="col-lg-6 col-6 txt-reason" name="REASON"></textarea>
                    </div>
                    <div class="col-lg-7 col-12">
                        <button type="submit" class="btn btn-success right">Xác nhận</button>
                    </div>
                </div>
            }
        </div>
        <div class="card-body">

        </div>
    </div>

</div>

Human/Areas/Admin/Views/Leave/Edit.cshtml
@model Human.Areas.Admin.Models.LeaveModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Phép";
    ViewBag.active = 3;
}
@section meta{
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="Chỉnh sửa phép" />
    <meta name="author" content="" />

}

@section LoadJs{
    <script src="~/Areas/Assets/js/admin/Leave.js"></script>
}
@{
    var formatString = "{0:0,0}";
    var num = 0;
}

<div class="container">
    <div class="form">
        <div class="btn-back"><a href="~/Admin/Leave/Index"><i class="fa fa-arrow-left"></i></a></div>

        <div class="card-header leave-header">
            @using (Html.BeginForm("InsertLeave", "Leave", FormMethod.Post))
            {
                <input type="hidden" value="@Model.T_Leave.EMPLOYEE_ID" name="EMPLOYEE_ID" />
                <input type="hidden" value="@Model.T_Leave.KINDLEAVE_ID" id="kindleave_id" />
                <div class="row col-12">
                    <div class="col-lg-5 ">
                        <label class="header-child col-3">Mã NV:</label>
                        <input class="col-6" name="EMP_CODE" id="EMP_CODE" value="@Model.T_Leave.EMP_CODE" readonly>

                    </div>
                    <div class="col-lg-5 ">
                        <label class="header-child col-3">Họ tên:</label>
                        <input class="col-6" name="FULLNAME" id="FULLNAME" value="@Model.T_Leave.FULLNAME" readonly>
                    </div>
                </div>
                <div class="row col-12">
                    <div class="col-lg-5 ">
                        <label class="header-child col-3">Loại phép:</label>
                        <select class="col-6 " name="KINDLEAVE_ID" id="ListKindLeave">
                            @foreach (var item in Model.LST_KINDLEAVE)
                            {
                                <option value="@item.KINDLEAVE_ID" @Html.Raw(item.KINDLEAVE_ID==Model.T_Leave.KINDLEAVE_ID?"Selected":"")>@item.NAMELEAVE_VI</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="row col-12">
                    <div class="col-lg-5 ">
                        <label class="header-child col-3">Từ ngày:</label>
                        <input id="LEAVE_STARTDATE" type="date" readonly class="col-6 col-lg-6" name="LEAVE_STARTDATE" value="@Model.T_Leave.LEAVE_STARTDATE.ToString("yyyy-MM-dd")" />
                    </div>
                    <div class="col-lg-5 ">
                        <label class="header-child col-3">Đến ngày:</label>
                        <input id="LEAVE_ENDDATE" type="date" readonly class="col-6 col-lg-6" name="LEAVE_ENDDATE" value="@Model.T_Leave.LEAVE_ENDDATE.ToString("yyyy-MM-dd")" />
                    </div>
                </div>
                <div class="row col-12">
                    <div class="col-lg-5 ">
                        <label class="header-child col-3">Số giờ:</label>
                        <select class="col-6" name="HOURS">
                            <option value="4" @Html.Raw(Model.T_Leave.HOURS==4?"selected":"")>4</option>
                            <option value="8" @Html.Raw(Model.T_Leave.HOURS==8?"selected":"")>8</option>
                        </select>
                    </div>
                    <div class="col-lg-5  hidden-item">
                        <label class="header-child col-5">Compt for month:</label>
                        <input class="col-6" name="COM_MONTH" value="@Model.T_Leave.COM_MONTH" />
                    </div>
                    <div class="col-lg-5  hidden-item">
                        <label class="header-child col-3">year:</label>
                        <input class="col-6" name="COM_YEAR" value="@Model.T_Leave.COM_YEAR" />
                    </div>
                </div>
                <div class="row col-12">
                    <div class="col-lg-5 ">
                        <label class="header-child col-3">Lý do:</label>

                        <textarea type="text" class="col-6 col-lg-6 txt-reason" name="REASON">@Model.T_Leave.REASON</textarea>
                    </div>
                    <div class="col-12 col-lg-7">
                        <button type="submit" class="btn btn-success right">Xác nhận</button>
                    </div>
                </div>
            }
        </div>
        <div class="card-body">

        </div>
    </div>

</div>